max_distance: 1.50 # Метры
max_angle: 60.0 # Градусы
angle_distance: 0.5 # Метры
quantity: 1 # Количество
point_class: -1 # Класс новых точек, -1 — исходный по первой точке в паре
time_diff: 0.06 # Разница во времени между точками в секундах
ignore_classes: [12, 13, 202, 203] # Игнорировать точки с этими классами (любая в паре)
test_mode: false # Тестовый режим
input_folder: "./01_input" # Папка с входными данными
output_folder: "./02_output" # Папка с выходными данными
max_workers: 4 # Максимальное количество потоков
workers: true # Использовать потоки
final_sort: true # Сортировать финальные точки по времени
